version: "3.6"

services:

  database:
    build: database
    restart: always
    environment:
      POSTGRESQL_ROOT_USER: postgres
      POSTGRESQL_ROOT_PASSWORD: postgres
      POSTGRESQL_DATABASE: hwproj
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - hwproj
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.10-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - hwproj

  runner:
    build: runner
    restart: on-failure
    depends_on:
      - database
      - rabbitmq
    links:
      - database
      - rabbitmq
    networks:
      - hwproj
    ports:
      - "8081:8081"

  server:
    build: web-server/hwproj
    restart: on-failure
    depends_on:
      - database
      - rabbitmq
      - runner
    links:
      - database
      - rabbitmq
      - runner
    networks:
      - hwproj
    ports:
      - "8080:8080"

networks:
  hwproj: