version: "3.6"

services:

  database:
    build: ./src/database/
    restart: always
    environment:
      POSTGRESQL_ROOT_USER: postgres
      POSTGRESQL_ROOT_PASSWORD: postgres
      POSTGRESQL_DATABASE: hwproj
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - postgres
    ports:
      - "5432:5432"

  server:
    build: .
    restart: on-failure
    depends_on:
      - database
    links:
      - database
    networks:
      - postgres
    ports:
      - "8080:8080"

networks:
  postgres: