version: '3.6'

services:
  database:
    build: src/database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hwproj
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - runner
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.10-management
    restart: always
    ports:
        - "15672:15672"
        - "5672:5672"
    networks:
      - runner

  app:
    build: .
    restart: on-failure
    depends_on:
      - database
      - rabbitmq
    links:
      - database
      - rabbitmq
    networks:
      - runner
    ports:
      - "8080:8080"

networks:
  runner: